# Generated by Django 5.2.8 on 2025-12-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Equipamento/Kit')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(default='PDV', help_text='Ex: PDV, Redes, Periférico, Servidor', max_length=50)),
            ],
            options={
                'verbose_name': 'Item Base',
                'verbose_name_plural': 'Itens Base',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('filial', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Código Filial (Java/ID)')),
                ('nome_filial', models.CharField(max_length=150, verbose_name='Nome da Filial')),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_banco_12', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Banco 12')),
                ('hist', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ABERTURA', 'Em Abertura'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
