# Generated by Django 5.2.8 on 2025-12-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loja_logomarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='loja',
            name='insc_estaudal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='loja',
            name='regiao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Região'),
        ),
    ]
