# Generated by Django 5.2.8 on 2025-12-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loja_cnpj_loja_insc_estaudal_loja_regiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='insc_estaudal',
            new_name='insc_estadual',
        ),
    ]
