# Generated by Django 5.2.8 on 2026-01-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_insc_estaudal_loja_insc_estadual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBase',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
