# Generated by Django 5.2.8 on 2025-12-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto Principal',
                'verbose_name_plural': 'Projetos Principais',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='projetos.projeto', verbose_name='Projeto Principal')),
            ],
            options={
                'verbose_name': 'Categoria de Projeto',
                'verbose_name_plural': 'Categorias de Projetos',
                'unique_together': {('projeto', 'nome')},
            },
        ),
    ]
