# Generated by Django 5.2.8 on 2026-01-13 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0003_categoria_remove_chamado_categoria_equipamento_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={},
        ),
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_ativos.equipamento')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='projetos.kit')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
