# Generated by Django 5.2.8 on 2026-01-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_options_projeto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkit',
            name='uso_no_kit',
            field=models.CharField(choices=[('pdv', 'PDV'), ('tc', 'Terminal de Consulta (TC)'), ('hibrido', 'Híbrido (PDV + TC)'), ('gerencia', 'Gerência'), ('farmacia', 'Farmácia'), ('outro', 'Outro')], default='pdv', max_length=50),
        ),
    ]
