# Generated by Django 5.2.8 on 2026-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0005_alter_equipamento_exige_ativo'),
        ('projetos', '0003_itemkit_uso_no_kit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemkit',
            options={'verbose_name': 'Item do Kit', 'verbose_name_plural': 'Itens do Kit'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['projeto', 'nome'], 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterField(
            model_name='itemkit',
            name='uso_no_kit',
            field=models.CharField(choices=[('pdv', 'PDV'), ('tc', 'Terminal de Consulta (TC)'), ('hibrido', 'Híbrido (PDV + TC)'), ('gerencia', 'Gerência'), ('farmacia', 'Farmácia'), ('outro', 'Outro')], default='pdv', max_length=50, verbose_name='Ocasião de Uso'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='itemkit',
            unique_together={('kit', 'equipamento', 'uso_no_kit')},
        ),
    ]
