# Generated by Django 5.2.8 on 2025-12-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.CharField(max_length=50, unique=True, verbose_name='Chamado / Nº')),
                ('data_separacao', models.DateField(blank=True, null=True, verbose_name='Data Separação')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data Saída')),
                ('smartx', models.CharField(choices=[('A_SEPARACAO', 'A. Separação'), ('A_NF', 'A. NF'), ('A_COLETA', 'A. Coleta'), ('A_BAIXA', 'A. Baixa'), ('FINALIZADO', 'Finalizado')], default='A_AGUARDANDO', max_length=50, verbose_name='Smartx / Status do Chamado')),
                ('volume', models.IntegerField(verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Equipamento')),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento',
                'verbose_name_plural': 'Tipos de Equipamento',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipamento', models.CharField(max_length=50, verbose_name='C. Equipamento')),
                ('nr_serie', models.CharField(max_length=100, unique=True, verbose_name='Nº de Série')),
                ('ativo_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Ativo')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('USO', 'Em Uso'), ('BAIXA', 'Baixado'), ('MOVIMENTACAO', 'Em Movimentação')], default='ESTOQUE', max_length=20, verbose_name='Status Atual')),
                ('chamado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_ativos.chamado', verbose_name='Chamado Associado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_ativos.tipoequipamento', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
