# Generated by Django 5.2.8 on 2025-12-10 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projetos.categoria', verbose_name='Categoria do Projeto'),
            preserve_default=False,
        ),
    ]
