# Generated by Django 5.2.8 on 2026-01-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0002_chamado_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('exige_ativo', models.BooleanField(default=True, verbose_name='Este item possui Ativo/Patrimônio?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_ativos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='AtivoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_ativo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('num_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('estoque', 'Em Estoque'), ('enviado', 'Enviado'), ('defeito', 'Defeito')], default='estoque', max_length=50)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_ativos.equipamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Ativo',
        ),
        migrations.DeleteModel(
            name='TipoEquipamento',
        ),
        migrations.DeleteModel(
            name='Chamado',
        ),
    ]
