# Generated by Django 5.2.8 on 2026-01-14 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0003_categoria_remove_chamado_categoria_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativofisico',
            options={'verbose_name': 'Ativo Físico', 'verbose_name_plural': 'Ativos Físicos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name': 'Modelo de Equipamento', 'verbose_name_plural': 'Modelos de Equipamentos'},
        ),
        migrations.AlterField(
            model_name='ativofisico',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='controle_ativos.equipamento'),
        ),
        migrations.AlterField(
            model_name='ativofisico',
            name='status',
            field=models.CharField(choices=[('estoque', 'Em Estoque'), ('enviado', 'Enviado'), ('defeito', 'Com Defeito'), ('manutencao', 'Em Manutenção')], default='estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_ativos.categoria'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='exige_ativo',
            field=models.BooleanField(default=True, help_text='Marque apenas se o item tiver etiqueta de patrimonio', verbose_name='Possui Patrimônio?'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(help_text='Ex: LCD, Touch, Laser', max_length=50),
        ),
    ]
