# Generated by Django 5.2.8 on 2026-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ativos', '0004_alter_ativofisico_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='exige_ativo',
            field=models.BooleanField(default=True, help_text='Marque apenas se o item tiver etiqueta de patrimônio', verbose_name='Possui Patrimônio?'),
        ),
    ]
