# Generated by Django 5.2.8 on 2026-01-14 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_itembase_delete_projeto'),
        ('projetos', '0003_itemkit_uso_no_kit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('kit_utilizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.kit', verbose_name='Modelo de Kit')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja', verbose_name='Loja de Destino')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.projeto', verbose_name='Projeto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Registro de Saída',
                'verbose_name_plural': 'Registros de Saída',
            },
        ),
        migrations.CreateModel(
            name='ItemBipado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento_tipo', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('ativo_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ativo ID')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_bipados', to='registro.registrosaida')),
            ],
        ),
    ]
