# Generated by Django 5.2.8 on 2026-01-14 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_itembase_delete_projeto'),
        ('projetos', '0003_itemkit_uso_no_kit'),
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosaida',
            options={},
        ),
        migrations.AddField(
            model_name='registrosaida',
            name='numero_chamado',
            field=models.CharField(default=0, max_length=50, verbose_name='Número do Chamado / Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosaida',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itembipado',
            name='ativo_id',
            field=models.CharField(default=0, max_length=100, verbose_name='Ativo ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itembipado',
            name='num_serie',
            field=models.CharField(max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='kit_utilizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.kit'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
