# Generated by Django 5.2.8 on 2026-01-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registrosaida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembipado',
            name='codigo_java',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
